export const INTEREST_OPTIONS = [
  "Technology",
  "AI",
  "Programming",
  "Science",
  "Education",
  "Engineering",
  "Business",
  "Startups",
  "Gaming",
  "Movies",
  "Music",
  "Books",
  "Travel",
  "Photography",
  "Art",
  "History",
  "Philosophy",
  "Fitness",
  "Languages",
  "Career",
  "Study",
  "Culture",
  "Space",
  "Psychology",
  "Design",
  "Entrepreneurship",
];

export const INTENT_OPTIONS = [
  "Just talk",
  "Meet new people",
  "Make friends",
  "Learn something",
  "Teach something",
  "Language practice",
  "Study together",
  "Brainstorm",
  "Work on ideas",
  "Discuss technology",
  "Creative discussion",
  "Networking",
  "Knowledge exchange",
  "Completely random",
];

export const CONVERSATION_STYLE_OPTIONS = [
  "Casual",
  "Deep",
  "Curious",
  "Technical",
  "Friendly",
  "Fast-paced",
  "Relaxed",
  "Structured",
  "Short conversations",
  "Long conversations",
];

export const LANGUAGE_OPTIONS = [
  "English",
  "Hindi",
  "Spanish",
  "French",
  "German",
  "Mandarin Chinese",
  "Japanese",
  "Korean",
  "Portuguese",
  "Russian",
  "Arabic",
  "Bengali",
  "Odia",
  "Tamil",
  "Telugu",
  "Marathi",
  "Gujarati",
  "Punjabi",
  "Italian",
  "Dutch",
];
